#ifndef TONTOOLKIT_GUI_GLOBAL_H
#define TONTOOLKIT_GUI_GLOBAL_H

#include <QtCore/qglobal.h>

#ifndef QT_STATIC
#if defined(LIBQTTONTOOLKIT_GUI_LIBRARY)
#  define LIBQTTONTOOLKIT_GUI_EXPORT Q_DECL_EXPORT
#else
#  define LIBQTTONTOOLKIT_GUI_EXPORT Q_DECL_IMPORT
#endif
#else
#define LIBQTTONTOOLKIT_GUI_EXPORT
#endif

#endif // TONTOOLKIT_GUI_GLOBAL_H
